version: '3.9'
services:
  fast-cloud-gateway:
    image: makunet:1.0
    container_name: fast-cloud-gateway
    ports:
      - 8080:8080
    env_file:
      - app.env
    volumes:
      - /work/www/fast-cloud/fast-cloud-gateway.jar:/app/app.jar
  fast-cloud-system:
    image: makunet:1.0
    container_name: fast-cloud-system
    env_file:
      - app.env
    volumes:
      - /work/www/fast-cloud/fast-cloud-system.jar:/app/app.jar
#  fast-cloud-quartz:
#    image: makunet:1.0
#    container_name: fast-cloud-quartz
#    env_file:
#      - app.env
#    volumes:
#      - /work/www/fast-cloud/fast-cloud-quartz.jar:/app/app.jar
#  fast-cloud-message:
#    image: makunet:1.0
#    container_name: fast-cloud-message
#    env_file:
#      - app.env
#    volumes:
#      - /work/www/fast-cloud/fast-cloud-message.jar:/app/app.jar