server:
  port: 8080

spring:
  application:
    name: maku-cloud-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: maku-cloud-system
          uri: lb://maku-cloud-system
          order: 1
          predicates:
            - Path=/sys/**
          filters:
            - RewritePath=/online/(?<path>/?.*), /sys/online/$\{path}
            - StripPrefix=1
        - id: maku-module-quartz
          uri: lb://maku-module-quartz
          order: 2
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        - id: maku-module-message
          uri: lb://maku-module-message
          order: 3
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
        - id: maku-module-monitor
          uri: lb://maku-module-monitor
          order: 4
          predicates:
            - Path=/monitor/**
          filters:
            - StripPrefix=1
        - id: maku-cloud-new
          uri: lb://maku-cloud-new
          order: 999
          predicates:
            - Path=/new/**
          filters:
            - StripPrefix=1
        - id: maku-module-generator
          uri: lb://maku-module-generator
          order: 1000
          predicates:
            - Path=/maku-generator/**
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml



knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      version : openapi3


---


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
